#include "/Engine/Private/Common.ush"

Texture2D InputTexture;
SamplerState InputSampler;
float2 InvSize;
float2 Direction;
float BlurRadius;
int BlurQuality;

void BlurPS(
	noperspective float4 UVAndScreenPos : TEXCOORD0,
	in FStereoPSInput StereoInput,
	out float4 OutColor : SV_Target0)
{
	const float2 UV = UVAndScreenPos.xy;
	const float4 center = InputTexture.SampleLevel(InputSampler, UV, 0);
	
	float4 color = 0;
	if (BlurQuality==2)
	{
		float2 off1 = 1.411764705882353 * Direction * BlurRadius;
		float2 off2 = 3.2941176470588234 * Direction * BlurRadius;
		float2 off3 = 5.176470588235294 * Direction * BlurRadius;
		color += center * 0.1964825501511404;
		color += InputTexture.SampleLevel(InputSampler, UV + off1 * InvSize,0) * 0.2969069646728344;
		color += InputTexture.SampleLevel(InputSampler, UV - off1 * InvSize,0) * 0.2969069646728344;
		color += InputTexture.SampleLevel(InputSampler, UV + off2 * InvSize,0) * 0.09447039785044732;
		color += InputTexture.SampleLevel(InputSampler, UV - off2 * InvSize,0) * 0.09447039785044732;
		color += InputTexture.SampleLevel(InputSampler, UV + off3 * InvSize,0) * 0.010381362401148057;
		color += InputTexture.SampleLevel(InputSampler, UV - off3 * InvSize,0) * 0.010381362401148057;
	}
	else if (BlurQuality==1)
	{
		float2 off1 = 1.3846153846 * Direction * BlurRadius;
		float2 off2 = 3.2307692308 * Direction * BlurRadius;
		color += center * 0.2270270270;
		color += InputTexture.SampleLevel(InputSampler, UV + off1 * InvSize,0) * 0.3162162162;
		color += InputTexture.SampleLevel(InputSampler, UV - off1 * InvSize,0) * 0.3162162162;
		color += InputTexture.SampleLevel(InputSampler, UV + off2 * InvSize,0) * 0.0702702703;
		color += InputTexture.SampleLevel(InputSampler, UV - off2 * InvSize,0) * 0.0702702703;
	}
	else
	{
		float2 offset = 1.3333333333333333 * Direction * BlurRadius;
		color += center * 0.29411764705882354;
		color += InputTexture.SampleLevel(InputSampler, UV + offset * InvSize,0) * 0.35294117647058826;
		color += InputTexture.SampleLevel(InputSampler, UV - offset * InvSize,0) * 0.35294117647058826;
	}
	
	OutColor=float4(color.rgb,center.a);
}
